version: '3.4'

services:

  robot-core:
    build:
      context: .
      dockerfile: Dockerfile 
      network: host
    environment:
      - ROS_ROOT=/opt/ros/kinetic/share/ros
      - ROS_PACKAGE_PATH=/home/baxter/hardware_ws/src:/opt/ros/kinetic/share
      - ROS_MASTER_URI=http://011502P0001.local:11311
      - ROS_PYTHON_VERSION=2
      - ROS_VERSION=1
      - ROSLISP_PACKAGE_DIRECTORIES=/home/baxter/catkin_ws/devel/share/common-lisp
      - __ROS_PROMPT=1
      - ROS_DISTRO=kinetic
      - ROS_IP=10.0.0.155
      - ROS_ETC_DIR=/opt/ros/kinetic/etc/ros
    privileged: true
    container_name: astra_launch 
    network_mode: host
    # command: rostopic pub /test std_msgs/String hello
    extra_hosts:
      - "011502P0001.local:10.0.0.10"
    restart: always
  
   
